/**
 * PDF Generator Service — Converts claim generated_text (Markdown) to a clean, styled PDF.
 * Uses pdfkit for zero-system-dependency PDF generation.
 *
 * Design: Pure service — no DB access, takes text + metadata and returns Buffer.
 */

import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface ClaimPdfInput {
  claimId: string;
  companyName: string;
  companyCountry: string;
  estimatedAmount: number;
  rdExpensesTotal: number;
  createdAt: Date;
  generatedText: string;
}

@Injectable()
export class PdfGeneratorService {
  private readonly logger = new Logger(PdfGeneratorService.name);

  async generateClaimPdf(input: ClaimPdfInput): Promise<Buffer> {
    this.logger.log(`Generating PDF for claim ${input.claimId}`);

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 60, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Cover / Header ─────────────────────────────────────────────
      doc
        .fillColor('#06b6d4')
        .fontSize(28)
        .font('Helvetica-Bold')
        .text('GrantAI', { align: 'center' });

      doc
        .fillColor('#1e293b')
        .fontSize(14)
        .font('Helvetica')
        .text('R&D Tax Credit Claim', { align: 'center' });

      doc.moveDown(0.5);

      // Divider
      doc
        .moveTo(60, doc.y)
        .lineTo(doc.page.width - 60, doc.y)
        .strokeColor('#06b6d4')
        .lineWidth(2)
        .stroke();

      doc.moveDown(1);

      // ── Claim Summary Table ─────────────────────────────────────────
      this.renderSummaryRow(doc, 'Claim ID:', input.claimId);
      this.renderSummaryRow(doc, 'Company:', input.companyName);
      this.renderSummaryRow(doc, 'Country:', input.companyCountry);
      this.renderSummaryRow(
        doc,
        'Generated:',
        input.createdAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }),
      );
      this.renderSummaryRow(doc, 'R&D Qualifying Expenses:', `$${input.rdExpensesTotal.toLocaleString()}`);

      // Estimated Credit — highlighted
      doc
        .fillColor('#06b6d4')
        .font('Helvetica-Bold')
        .fontSize(11)
        .text('Estimated Credit:  ', { continued: true })
        .text(`$${input.estimatedAmount.toLocaleString()}`)
        .fillColor('#1e293b')
        .font('Helvetica')
        .fontSize(11);

      doc.moveDown(1);

      // Divider
      doc
        .moveTo(60, doc.y)
        .lineTo(doc.page.width - 60, doc.y)
        .strokeColor('#e2e8f0')
        .lineWidth(1)
        .stroke();

      doc.moveDown(1);

      // ── Claim Body (Markdown → Plain text rendering) ────────────────
      const lines = input.generatedText.split('\n');
      for (const line of lines) {
        if (line.startsWith('# ')) {
          doc
            .fillColor('#0f172a')
            .font('Helvetica-Bold')
            .fontSize(16)
            .text(line.replace(/^# /, ''));
          doc.moveDown(0.4);
        } else if (line.startsWith('## ')) {
          doc
            .fillColor('#06b6d4')
            .font('Helvetica-Bold')
            .fontSize(13)
            .text(line.replace(/^## /, ''));
          doc.moveDown(0.3);
        } else if (line.startsWith('### ')) {
          doc
            .fillColor('#1e293b')
            .font('Helvetica-Bold')
            .fontSize(12)
            .text(line.replace(/^### /, ''));
          doc.moveDown(0.3);
        } else if (line.startsWith('**') && line.endsWith('**')) {
          doc
            .fillColor('#334155')
            .font('Helvetica-Bold')
            .fontSize(11)
            .text(line.replace(/\*\*/g, ''));
          doc.moveDown(0.2);
        } else if (line.trim() === '') {
          doc.moveDown(0.5);
        } else {
          // Strip any remaining markdown bold markers
          const cleaned = line.replace(/\*\*(.*?)\*\*/g, '$1').trim();
          if (cleaned) {
            doc
              .fillColor('#334155')
              .font('Helvetica')
              .fontSize(10.5)
              .text(cleaned, { lineGap: 3 });
          }
        }
      }

      doc.moveDown(2);

      // ── Footer ──────────────────────────────────────────────────────
      doc
        .moveTo(60, doc.y)
        .lineTo(doc.page.width - 60, doc.y)
        .strokeColor('#e2e8f0')
        .lineWidth(1)
        .stroke();

      doc.moveDown(0.5);
      doc
        .fillColor('#94a3b8')
        .font('Helvetica')
        .fontSize(9)
        .text(
          `This document was generated by GrantAI on ${new Date().toISOString()}. It is intended for informational purposes only and does not constitute legal or tax advice.`,
          { align: 'center' },
        );

      doc.end();
    });
  }

  private renderSummaryRow(doc: PDFKit.PDFDocument, label: string, value: string) {
    doc
      .fillColor('#64748b')
      .font('Helvetica-Bold')
      .fontSize(11)
      .text(`${label}  `, { continued: true })
      .fillColor('#1e293b')
      .font('Helvetica')
      .text(value);
    doc.moveDown(0.3);
  }
}
